targetCustomizations:
- name: microk8s
  clusterSelector:
    matchLabels:
      provider: kind
  helm:
    values:
      rabbitmqServer:
        persistence:        
          storage: 2Gi
        resources:
          requests:
            memory: 2.5Gi
          limits:
            memory: 2.5Gi
- name: gke
  clusterSelector:
    matchLabels:
      provider: gke
  helm:
    values:
      rabbitmqServer:
        persistence:
          storageClassName: premium-rwo
      ingress:        
        annotations:
          kubernetes.io/ingress.global-static-ip-name: "gke-rmq-static-ip"
- name: openshift
  clusterSelector:
    matchLabels:
      provider: openshift
  helm:
    values:
      ingress:
        host: rmq-demo.apps.os2.openshift.edge-clusters.net        
  
