targetCustomizations:
- name: microk8s-clusters
  clusterSelector:
    matchLabels:
      provider: kind
  helm:
    values:
      rabbitmqServer:
        persistence:        
          storage: 4Gi
- name: gke-clusters
  clusterSelector:
    matchLabels:
      provider: gke
  helm:
    values:
      rabbitmqServer:
        persistence:
          storageClassName: standard
      ingress:        
        annotations:
          kubernetes.io/ingress.global-static-ip-name: "gke-rmq-static-ip"
- name: openshift-clusters
  clusterSelector:
    matchLabels:
      provider: openshift
  helm:
    values:
      ingress:
        host: rmq-demo.apps.os2.openshift.edge-clusters.net        
  
