# Default values for rmq-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

publisher:
  imageRepository:  debbabi/rmq-publisher
  imageTag: 0.2.0-rc.4

consumer:
  imageRepository:  debbabi/rmq-consumer
  imageTag: 0.2.0-rc.4

rabbitmqServer:
  persistence:
    storageClassName:
    storage: 10Gi
  resources:
    requests:
      cpu: 900m
      memory: 2Gi
    limits:
      cpu: 900m
      memory: 2Gi
