# Default values for rmq-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

publisher:
  imageRepository:  debbabi/rmq-publisher
  imageTag: 0.1.2

consumer:
  imageRepository:  debbabi/rmq-consumer
  imageTag: 0.1.2

rabbitmqServer:
  persistence:
    storageClassName:
    storage: 3Gi
