# Default values for rmq-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

publisher:
  imageRepository:  debbabi/rmq-publisher
  imageTag: 0.2.0-rc.7

consumer:
  imageRepository:  debbabi/rmq-consumer
  imageTag: 0.2.0-rc.7

rabbitmqServer:
  persistence:
    storageClassName:
    storage: 10Gi
  resources:
    requests:
      cpu: 800m
      memory: 1.5Gi
    limits:
      cpu: 900m
      memory: 1.5Gi
    
ingress:
  host: ""
