version: "3.9"
services:
  publisher:
    image: "rmq-publisher"
    ports:
      - "4001:4001"
    environment:
      RABBITMQ_HOST: "rabbitmq"
  consumer:
    image: "rmq-consumer"
    ports:
      - "4002:4002"
    environment:
      RABBITMQ_HOST: "rabbitmq"
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "15672:15672"
      - "5672:5672"
