--- 
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata: 
  name: rmq-demo
  namespace: edge-clusters
spec: 
  paths: 
    - app/charts/rmq-demo
  repo: "https://github.com/edge-orchestration/app-fleet-demo"
  branch: main
  targets: 
    - 
      clusterSelector: {}
      name: all-clusters