apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmqserver
spec:
  replicas: 1
  persistence:
    storage: {{ .Values.rabbitmq-server.persistence.storage }}
    {{ if .Values.rabbitmq-server.persistence.storageClassName }}
    storageClassName: {{ .Values.rabbitmq-server.persistence.storageClassName | quote }}
    {{- end }}
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 800m
      memory: 1Gi
