apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rmq-publisher-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
  labels:
    app: rmq-publisher
spec:
  rules:
  - http:
      paths:
      - path: /publisher
        pathType: Prefix
        backend:
          service:
            name: rmq-publisher
            port:
              number: 4001
