---
apiVersion: v1
kind: Service
metadata:
  name: rmq-publisher
  labels:
    app: rmq-publisher
spec:
  type: ClusterIP
  selector:
    app: rmq-publisher
  ports:
  - protocol: TCP
    port: 4001
    targetPort: 4001
    name: rmq-publisher