---
apiVersion: v1
kind: Service
metadata:
  name: rmq-consumer
  labels:
    app: rmq-consumer
spec:
  type: NodePort
  selector:
    app: rmq-consumer
  ports:
  - protocol: TCP
    port: 4002
    targetPort: 4002