apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rmq-publisher-ingress
  annotations:
    traefik.ingress.kubernetes.io/frontend-entry-points: http,https
    ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    app: rmq-publisher
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rmq-publisher
            port:
              # name: rmq-publisher
              number: 4001
