apiVersion: networking.k8s.io/v1
kind: Ingress
spec:
  rules:
  - http:
      paths:
      - path: /consumer
        pathType: Prefix
        backend:
          service:
            name: rmq-publisher
            port:
              number: 80
